# Driver
driver: org.postgresql.Driver

# URL de conexión (ajusta el nombre de la BD)
url: jdbc:postgresql://localhost:5432/tienda

# Usuario
username: user1

# Contraseña
password: usuario123

# Archivo changelog
changeLogFile: changelog.sql